### ISSUE TITLE
@typescript-eslint/no-unnecessary-condition errors in GenerateNM2.ts

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-tscodegen#24]
There are a number of places in the file with the following pattern:

```ts
function translateSpecFunctionParam(
  param: FunctionTypeAnnotationParam,
): string {
  switch (param.typeAnnotation.type) {
   ...
    case 'ReservedFunctionValueTypeAnnotation':
      if (param.typeAnnotation.name !== 'RootTag')
        throw new Error(
          `Unknown reserved function: ${param.typeAnnotation.name} in translateSpecFunctionParam`,
        );
      return 'double';
  ...
  }
}
```

The TypeScript compiler seems to always evaluate `param.typeAnnotation.name` to the 'RootTag' literal, so it believes we will always throw an error in this case. Unsure if this is an issue with tscodegen typings or faulty logic in GenerateNM2.

**Comment by ZihanChen-MSFT** [comment]
Does the latest release fix the issue?
